### Introduction To Pandas Module
Here, we are learning data analysis. Pandas is a software library written for the Python programming language that helps with data manipulation and analysis. It offers various data structures which help in the manipulation of data. <br>
One of the data structures used is DataFrame.<br>
DataFrame is used as a way to store data in a rectangular grid.<br>
Similar to how data is stored in Microsoft Excel.
### Installation
We can easily install this library using the terminal. Follow the steps given below to install Pandas:<br>
Step 1: Go to the Windows PowerShell.<br>
Step 2: We can install pandas with the help of pip easily. Head over to the directory where you want to install the pandas and fire the below command:<br>
__pip install pandas__<br>
This is very simple to install.

In [ ]:
# !pip install pandas

### Other way to install
If the above steps do not work for you, here is another way to install:<br>
Step 1: Go to your browser. Search for __python unofficial binaries__, or click <br>
https://www.lfd.uci.edu/~gohlke/pythonlibs/<br> 
and you will be redirected to the binary page.<br>
Step 2: To download the library, search for pandas – Ctrl + F will help you. Download pandas library based on your python version. <br>
Step 3: After the installation, head over to the directory where you've downloaded the pandas. <br>
Step 4: Right-click to open Windows PowerShell. Pip can help us with the installation. Just go to that location in your terminal and run the following command: <br>
__pip install pandas__ <br>
Complete this command by the TAB button so that the location of your folder is mentioned.

### import pandas
Once Pandas is installed, import it in your applications by adding the import keyword:<br>
__import pandas as pd__<br>
Now Pandas is imported and ready to use.

In [1]:
import pandas

In [2]:
students = {
    'Name': ["Muhammad Ayub ", " Ibraheem khan", "Muhammad Abid", "Shumail Khan","Qasim Ali"],
    'Marks': [80, 72, 77, 65, 15],
    'Class':["1st Year", "2nd Year", "1st Year", "3rd Year", "2nd Year"],
    'Age': [20, 21, 19, 22, 21]
}

In [3]:
df = pandas.DataFrame(students)

In [4]:
df

             Name  Marks     Class  Age
0  Muhammad Ayub      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19
3    Shumail Khan     65  3rd Year   22
4       Qasim Ali     15  2nd Year   21

### Pandas as pd
Pandas is usually imported under the pd alias.
#### alias: 
In Python alias are an alternate name for referring to the same thing.<br>
Create an alias with the as keyword while importing:<br>
__import pandas as pd__<br>
Now the Pandas package can be referred to as pd instead of pandas.

In [5]:
import pandas as pd

In [6]:
df = pd.DataFrame(students)

In [7]:
df

             Name  Marks     Class  Age
0  Muhammad Ayub      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19
3    Shumail Khan     65  3rd Year   22
4       Qasim Ali     15  2nd Year   21

### Checking Pandas Version
The version string is stored under __version__ attribute.

In [8]:
pd.__version__

'2.3.3'

## Saving to CSV and other extensions like excel

In [9]:
df.to_csv('pythonMonday.csv')

## Remove Index and saving the csv file

In [10]:
df.to_csv('pythonMondayRemoveIndex.csv', index=False)

## Show some rows from the Start

In [9]:
df.head()

             Name  Marks     Class  Age
0  Muhammad Ayub      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19
3    Shumail Khan     65  3rd Year   22
4       Qasim Ali     15  2nd Year   21

## Specify No of rows to show

In [10]:
df.head(3)

             Name  Marks     Class  Age
0  Muhammad Ayub      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19

In [11]:
df.tail(3)

            Name  Marks     Class  Age
2  Muhammad Abid     77  1st Year   19
3   Shumail Khan     65  3rd Year   22
4      Qasim Ali     15  2nd Year   21

In [12]:
df.tail()

             Name  Marks     Class  Age
0  Muhammad Ayub      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19
3    Shumail Khan     65  3rd Year   22
4       Qasim Ali     15  2nd Year   21

In [15]:
df.describe()

           Marks        Age
count   5.000000   5.000000
mean   61.800000  20.600000
std    26.771253   1.140175
min    15.000000  19.000000
25%    65.000000  20.000000
50%    72.000000  21.000000
75%    77.000000  21.000000
max    80.000000  22.000000

# Reading csv or other files

In [16]:
classData= pd.read_csv("pythonMondayRemoveIndex.csv")
classData

             Name  Marks     Class  Age
0  Muhammad Ayub      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19
3    Shumail Khan     65  3rd Year   22
4       Qasim Ali     15  2nd Year   21

In [17]:
classData= pd.read_csv("pythonMonday.csv")
classData

   Unnamed: 0            Name  Marks     Class  Age
0           0  Muhammad Ayub      80  1st Year   20
1           1   Ibraheem khan     72  2nd Year   21
2           2   Muhammad Abid     77  1st Year   19
3           3    Shumail Khan     65  3rd Year   22
4           4       Qasim Ali     15  2nd Year   21

In [18]:
classData.drop('Name', axis=1)

   Unnamed: 0  Marks     Class  Age
0           0     80  1st Year   20
1           1     72  2nd Year   21
2           2     77  1st Year   19
3           3     65  3rd Year   22
4           4     15  2nd Year   21

In [19]:
classData

   Unnamed: 0            Name  Marks     Class  Age
0           0  Muhammad Ayub      80  1st Year   20
1           1   Ibraheem khan     72  2nd Year   21
2           2   Muhammad Abid     77  1st Year   19
3           3    Shumail Khan     65  3rd Year   22
4           4       Qasim Ali     15  2nd Year   21

In [20]:
classData.drop(0, axis=0)

   Unnamed: 0            Name  Marks     Class  Age
1           1   Ibraheem khan     72  2nd Year   21
2           2   Muhammad Abid     77  1st Year   19
3           3    Shumail Khan     65  3rd Year   22
4           4       Qasim Ali     15  2nd Year   21

In [21]:
classData

   Unnamed: 0            Name  Marks     Class  Age
0           0  Muhammad Ayub      80  1st Year   20
1           1   Ibraheem khan     72  2nd Year   21
2           2   Muhammad Abid     77  1st Year   19
3           3    Shumail Khan     65  3rd Year   22
4           4       Qasim Ali     15  2nd Year   21

# Check the spelling

In [14]:
classData['Class']

NameError: name 'classData' is not defined

# Check the trail space

In [15]:
classData['Class ']

NameError: name 'classData' is not defined

# Corrected Spelling

In [16]:
classData['Name']

NameError: name 'classData' is not defined

# Check the head space

In [17]:
classData[' Name']

NameError: name 'classData' is not defined

In [18]:
type(classData['Name'])

NameError: name 'classData' is not defined

In [ ]:
classData['Age']

classData['gpa'][0]

In [19]:
classData['Age'][0]

NameError: name 'classData' is not defined

In [ ]:
classData['Age'][0]=90

In [ ]:
classData

In [20]:
classData['Age'][4]

NameError: name 'classData' is not defined

In [21]:
classData['Age'][4]=5

NameError: name 'classData' is not defined

In [ ]:
classData["Name"][4]

# Rename the column name

In [22]:
classData.rename(columns={'Age': 'AGE'})

NameError: name 'classData' is not defined

## Create Labels
With the index argument, you can name your own labels.

In [23]:
classData.index = ["First","Second", "Third", "Fourth", "Fifth"]
classData

NameError: name 'classData' is not defined

# Asignment

In [ ]:
classdata = classData.drop('Unnamed: 0', axis=1)
classData

# Inplace

In [24]:
classData.drop('Unnamed: 0', axis=1, inplace = True)
classData

NameError: name 'classData' is not defined

# Accessing the value in Dataframe

In [25]:
classData["Name"]

NameError: name 'classData' is not defined

In [26]:
classData["Name"]["Fifth"]

NameError: name 'classData' is not defined

## Pandas 
Pandas is an open source data analysis library written in Python.<br>
It uses the power and speed of numpy to make data analysis and preprocessing easy for data scientists.<br>
__Pandas__ is used to analyze data.<br>
Python data analysis using pandas is a great start to Exploratory Data Analysis (EDA) for a data scientist.

## Pandas Data Structure
Panda has two types of Data Structure:<br> 
    a) Series<br>
    b) Dataframe
### Series
It is a one dimentional array with indexes. It stores a single column or row of data in a Dataframe.<br>
It is a one dimensional array capable of holding any type of data.
### Dataframe
It is a tabular spreadsheet like structure representing rows each of which contains one or more columns.<br>
It is a multi dimensional array capable of holding any type of data.<br>
__Series__ is like a column, a __DataFrame__ is the whole table.

In [27]:
classData['Age']

NameError: name 'classData' is not defined

In [ ]:
 type(classData['Age'])

In [28]:
classData

NameError: name 'classData' is not defined

In [ ]:
type(classData)

In [ ]:
import numpy as np

In [ ]:
series1= pd.Series(np.random.rand())

In [29]:
series1

NameError: name 'series1' is not defined

In [ ]:
series1= pd.Series(np.random.rand(30))

In [30]:
series1

NameError: name 'series1' is not defined

In [ ]:
type(series1)

In [31]:
np.random.rand(3,4)

NameError: name 'np' is not defined

In [32]:
newDf = pd.DataFrame(np.random.rand(330,5))
# newDf = pd.DataFrame(np.random.rand(330,5), index=np.arange(330))

NameError: name 'np' is not defined

In [33]:
type(newDf)

NameError: name 'newDf' is not defined

In [ ]:
newDf.head(2)

In [34]:
newDf.tail(2)

NameError: name 'newDf' is not defined

In [ ]:
newDf.info()

In [35]:
newDf.describe()

NameError: name 'newDf' is not defined

In [ ]:
newDf.dtypes

# Change the value inside the dataframe

In [36]:
newDf[0][0]= 10000.0

NameError: name 'newDf' is not defined

In [37]:
newDf

NameError: name 'newDf' is not defined

In [ ]:
newDf.head()

# Transpose

In [38]:
newDf.T

NameError: name 'newDf' is not defined

# Sorting

In [39]:
newDf.sort_index(axis=0)

NameError: name 'newDf' is not defined

In [ ]:
newDf.sort_index(axis=0, ascending=False)

In [40]:
newDf.sort_index(axis=1)

NameError: name 'newDf' is not defined

In [ ]:
newDf.sort_index(axis=1, ascending=False)

In [41]:
newDf.head()

NameError: name 'newDf' is not defined

In [42]:
newDf[0][1]

NameError: name 'newDf' is not defined

In [ ]:
type(newDf[0])

In [43]:
newDf

NameError: name 'newDf' is not defined

## view

In [44]:
newDfView=newDf

NameError: name 'newDf' is not defined

In [ ]:
newDfView

In [45]:
newDfView[0][0]=765

NameError: name 'newDfView' is not defined

In [172]:
newDf.head()

          0         1         2         3         4
0       765  0.869805  0.874954  0.464529  0.111939
1  0.430962  0.517649  0.827469  0.745495  0.126307
2  0.245838  0.810678  0.931999  0.619516  0.018667
3  0.582559  0.717834  0.364970  0.389055  0.955452
4  0.779116  0.522410  0.292404  0.484660  0.765520

In [173]:
newDfView.head()

          0         1         2         3         4
0       765  0.869805  0.874954  0.464529  0.111939
1  0.430962  0.517649  0.827469  0.745495  0.126307
2  0.245838  0.810678  0.931999  0.619516  0.018667
3  0.582559  0.717834  0.364970  0.389055  0.955452
4  0.779116  0.522410  0.292404  0.484660  0.765520

In [174]:
newDfCopy=newDf.copy()

In [175]:
newDfCopy[0][0]=656

C:\Users\M Ayub\AppData\Local\Temp\ipykernel_8644\2532441962.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newDfCopy[0][0]=656
C:\Users\M Ayub\AppData\Local\Temp\ipykernel_8644\2532441962.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newDfCopy[0][0]=656

In [176]:
newDf.head()

          0         1         2         3         4
0       765  0.869805  0.874954  0.464529  0.111939
1  0.430962  0.517649  0.827469  0.745495  0.126307
2  0.245838  0.810678  0.931999  0.619516  0.018667
3  0.582559  0.717834  0.364970  0.389055  0.955452
4  0.779116  0.522410  0.292404  0.484660  0.765520

In [177]:
newDfCopy.head()

          0         1         2         3         4
0       656  0.869805  0.874954  0.464529  0.111939
1  0.430962  0.517649  0.827469  0.745495  0.126307
2  0.245838  0.810678  0.931999  0.619516  0.018667
3  0.582559  0.717834  0.364970  0.389055  0.955452
4  0.779116  0.522410  0.292404  0.484660  0.765520

In [62]:
import pandas as pd

# Create a sample DataFrame
data = {
    "Student": ["Ali", "Sara", "Bilal", "Hina"],
    "Marks": [85, 92, 76, 89],
    "Age": [20, 21, 19, 22]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

Original DataFrame:
   Student  Marks  Age
0     Ali     85   20
1    Sara     92   21
2   Bilal     76   19
3    Hina     89   22

In [64]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Student  4 non-null      object
 1   Marks    4 non-null      int64
 2   Age      4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 224.0+ bytes
None

In [65]:
print("\nDescribe:\n", df.describe())

Describe:
            Marks        Age
count   4.000000   4.000000
mean   85.500000  20.500000
std     6.952218   1.290994
min    76.000000  19.000000
25%    82.750000  19.750000
50%    87.000000  20.500000
75%    89.750000  21.250000
max    92.000000  22.000000

In [66]:
# -----------------------------
# 2. SORTING
# -----------------------------
print("\nSorting by Marks (descending):\n", df.sort_values("Marks", ascending=False))
print("\nSorting by Age (ascending):\n", df.sort_values("Age"))

Sorting by Marks (descending):
   Student  Marks  Age
1    Sara     92   21
3    Hina     89   22
0     Ali     85   20
2   Bilal     76   19

Sorting by Age (ascending):
   Student  Marks  Age
2   Bilal     76   19
0     Ali     85   20
1    Sara     92   21
3    Hina     89   22

In [67]:
# -----------------------------
# 3. TRANSPOSE
# -----------------------------
print("\nTransposed DataFrame:\n", df.T)

Transposed DataFrame:
            0     1      2     3
Student  Ali  Sara  Bilal  Hina
Marks     85    92     76    89
Age       20    21     19    22

## Slicing through loc function

In [102]:
import pandas as pd

# Sample DataFrame
data = {
    "Name": ["Ali", "Sara", "Bilal", "Hina"],
    "Marks": [85, 92, 76, 89],
    "Age": [20, 21, 19, 22]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

Original DataFrame:
     Name  Marks  Age
0    Ali     85   20
1   Sara     92   21
2  Bilal     76   19
3   Hina     89   22

In [103]:
# 1. Select row with label 2
print(df.loc[2])

Name     Bilal
Marks       76
Age         19
Name: 2, dtype: object

In [104]:
# 2. Select specific rows and columns by NAME
print(df.loc[1:3, ["Name", "Marks"]])

    Name  Marks
1   Sara     92
2  Bilal     76
3   Hina     89

In [105]:

# 3. Applying Filter: Conditional selection: students with Marks > 85
print(df.loc[df["Marks"] > 85])

   Name  Marks  Age
1  Sara     92   21
3  Hina     89   22

##  Slicing through iloc

In [106]:
df

    Name  Marks  Age
0    Ali     85   20
1   Sara     92   21
2  Bilal     76   19
3   Hina     89   22

In [107]:
# 1. Select row at index 0
print(df.iloc[0])

Name     Ali
Marks     85
Age       20
Name: 0, dtype: object

In [108]:
# 2. Select 2 rows and 2 columns by position
print(df.iloc[0:2, 0:2])

   Name  Marks
0   Ali     85
1  Sara     92

In [109]:
# 3. Select last row using negative index
print(df.iloc[-1])

Name     Hina
Marks      89
Age        22
Name: 3, dtype: object

# Dropping the Row

In [110]:
df

    Name  Marks  Age
0    Ali     85   20
1   Sara     92   21
2  Bilal     76   19
3   Hina     89   22

In [111]:
df.drop(0).head()

    Name  Marks  Age
1   Sara     92   21
2  Bilal     76   19
3   Hina     89   22

# Dropping the col

In [112]:
df.drop(['Age'], axis=1).head()

    Name  Marks
0    Ali     85
1   Sara     92
2  Bilal     76
3   Hina     89

In [113]:
df.head()

    Name  Marks  Age
0    Ali     85   20
1   Sara     92   21
2  Bilal     76   19
3   Hina     89   22

In [114]:
df.drop(['Age'], axis=1, inplace=True)

In [115]:
df.head()

    Name  Marks
0    Ali     85
1   Sara     92
2  Bilal     76
3   Hina     89

In [121]:
df.reset_index().head()

   index   Name  Marks
0      0    Ali     85
1      1   Sara     92
2      2  Bilal     76
3      3   Hina     89

In [122]:
df.reset_index(drop=True).head()

    Name  Marks
0    Ali     85
1   Sara     92
2  Bilal     76
3   Hina     89

In [123]:
df.head()

    Name  Marks
0    Ali     85
1   Sara     92
2  Bilal     76
3   Hina     89

In [124]:
df.reset_index(drop=True, inplace=True)

In [125]:
df.head()

    Name  Marks
0    Ali     85
1   Sara     92
2  Bilal     76
3   Hina     89

# Groupby
The groupby method allows you to group rows of data together and call aggregate functions

​
​

In [46]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [47]:
df = pd.DataFrame(data)

In [48]:
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

### Now you can use the .groupby() method to group rows together based off of a column name.
For instance let's group based off of Company. This will create a DataFrameGroupBy object:

In [49]:
df.groupby('Company')

##### You can save this object as a new variable:

In [53]:
by_comp = df.groupby("Company")
type(by_comp)

pandas.core.groupby.generic.DataFrameGroupBy

In [ ]:
df.groupby('Company'){"sales"

#### And then call aggregate methods of the object:

In [54]:
by_comp.mean()

TypeError: agg function failed [how->mean,dtype->object]

In [55]:
df.groupby('Company').mean()

TypeError: agg function failed [how->mean,dtype->object]

In [56]:
by_comp.std()

ValueError: could not convert string to float: 'Sam'

In [58]:
by_comp.min()

          Person  Sales
Company
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124

In [59]:
by_comp.max()

          Person  Sales
Company
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [13]:
by_comp.count()

         Person  Sales
Company
FB            2      2
GOOG          2      2
MSFT          2      2

In [14]:
by_comp.describe()

        Sales
        count   mean         std    min     25%    50%     75%    max
Company
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0