## LAB_NO_02_Part_02_22JZELE0480 

### University of Engineering and Technology Peshawar, Nowshera Campus

#### Course: Machine Learning Lab

#### Student Name: Ibraheem khan
#### Registration Number: 22jzele0480

# Introduction to Pandas Module

Pandas is a powerful open-source Python library used for data manipulation and analysis. It provides easy-to-use data structures like **Series** and **DataFrame**, which are essential for handling structured data (similar to Excel spreadsheets).

In this lab, we will explore the core concepts of Pandas including DataFrame creation, data inspection, file I/O operations, indexing, selection, and basic data analysis.

### Installation
We can easily install this library using the terminal. Follow the steps given below to install Pandas:<br>
Step 1: Go to the Windows PowerShell.<br>
Step 2: We can install pandas with the help of pip easily. Head over to the directory where you want to install the pandas and fire the below command:<br>
__pip install pandas__<br>
This is very simple to install.

In [ ]:
# !pip install pandas

### Importing Pandas
Once Pandas is installed, import it in your applications by adding the import keyword.

In [1]:
import pandas

In [2]:
# Creating sample student data as a Python dictionary
students = {
    'Name': ["Muhammad Ayub ", " Ibraheem khan", "Muhammad Abid", "Shumail Khan","Qasim Ali"],
    'Marks': [80, 72, 77, 65, 15],
    'Class':["1st Year", "2nd Year", "1st Year", "3rd Year", "2nd Year"],
    'Age': [20, 21, 19, 22, 21]
}

In [3]:
# Converting the dictionary into a Pandas DataFrame
df = pandas.DataFrame(students)

In [4]:
# Displaying the newly created DataFrame
df

             Name  Marks     Class  Age
0  Muhammad Ayub      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19
3    Shumail Khan     65  3rd Year   22
4       Qasim Ali     15  2nd Year   21

### Using Pandas with Alias `pd`
It is a standard convention to import pandas as `pd` for brevity.

In [5]:
import pandas as pd

In [6]:
# Creating DataFrame using the alias
df = pd.DataFrame(students)

In [7]:
df

             Name  Marks     Class  Age
0  Muhammad Ayub      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19
3    Shumail Khan     65  3rd Year   22
4       Qasim Ali     15  2nd Year   21

### Checking Pandas Version

In [8]:
pd.__version__

'2.3.3'

## Saving DataFrame to CSV Files

In [9]:
# Saving DataFrame to CSV with default index
df.to_csv('pythonMonday.csv')

In [10]:
# Saving without index column (cleaner output)
df.to_csv('pythonMondayRemoveIndex.csv', index=False)

## Inspecting the DataFrame

In [9]:
# Viewing the first few rows (by default 5)
df.head()

             Name  Marks     Class  Age
0  Muhammad Ayub      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19
3    Shumail Khan     65  3rd Year   22
4       Qasim Ali     15  2nd Year   21

In [10]:
# Viewing specific number of rows from the top
df.head(3)

             Name  Marks     Class  Age
0  Muhammad Ayub      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19

In [11]:
# Viewing last few rows
df.tail(3)

            Name  Marks     Class  Age
2  Muhammad Abid     77  1st Year   19
3   Shumail Khan     65  3rd Year   22
4      Qasim Ali     15  2nd Year   21

In [12]:
df.tail()

             Name  Marks     Class  Age
0  Muhammad Ayub      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19
3    Shumail Khan     65  3rd Year   22
4       Qasim Ali     15  2nd Year   21

In [15]:
# Statistical summary of numerical columns
df.describe()

           Marks        Age
count   5.000000   5.000000
mean   61.800000  20.600000
std    26.771253   1.140175
min    15.000000  19.000000
25%    65.000000  20.000000
50%    72.000000  21.000000
75%    77.000000  21.000000
max    80.000000  22.000000

## Reading CSV Files

In [16]:
# Reading CSV without index column
classData = pd.read_csv("pythonMondayRemoveIndex.csv")
classData

             Name  Marks     Class  Age
0  Muhammad Ayub      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19
3    Shumail Khan     65  3rd Year   22
4       Qasim Ali     15  2nd Year   21

In [17]:
# Reading CSV that includes index column
classData = pd.read_csv("pythonMonday.csv")
classData

   Unnamed: 0            Name  Marks     Class  Age
0           0  Muhammad Ayub      80  1st Year   20
1           1   Ibraheem khan     72  2nd Year   21
2           2   Muhammad Abid     77  1st Year   19
3           3    Shumail Khan     65  3rd Year   22
4           4       Qasim Ali     15  2nd Year   21

## Data Manipulation - Dropping Columns

In [18]:
# Dropping a column (returns new DataFrame)
classData.drop('Name', axis=1)

   Unnamed: 0  Marks     Class  Age
0           0     80  1st Year   20
1           1     72  2nd Year   21
2           2     77  1st Year   19
3           3     65  3rd Year   22
4           4     15  2nd Year   21

## Accessing Columns and Elements

In [19]:
classData

   Unnamed: 0            Name  Marks     Class  Age
0           0  Muhammad Ayub      80  1st Year   20
1           1   Ibraheem khan     72  2nd Year   21
2           2   Muhammad Abid     77  1st Year   19
3           3    Shumail Khan     65  3rd Year   22
4           4       Qasim Ali     15  2nd Year   21

In [20]:
# Dropping a row by index
classData.drop(0, axis=0)

   Unnamed: 0            Name  Marks     Class  Age
1           1   Ibraheem khan     72  2nd Year   21
2           2   Muhammad Abid     77  1st Year   19
3           3    Shumail Khan     65  3rd Year   22
4           4       Qasim Ali     15  2nd Year   21

## Renaming Columns and Setting Custom Index

In [22]:
# Renaming a column (returns new DataFrame)
classData.rename(columns={'Age': 'AGE'})

   Unnamed: 0            Name  Marks     Class  AGE
0           0  Muhammad Ayub      80  1st Year   20
1           1   Ibraheem khan     72  2nd Year   21
2           2   Muhammad Abid     77  1st Year   19
3           3    Shumail Khan     65  3rd Year   22
4           4       Qasim Ali     15  2nd Year   21

## Inplace Modifications

In [24]:
# Removing index column permanently (inplace)
classData.drop('Unnamed: 0', axis=1, inplace=True)

In [25]:
classData

             Name  Marks     Class  Age
0  Muhammad Ayub      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19
3    Shumail Khan     65  3rd Year   22
4       Qasim Ali     15  2nd Year   21

## Pandas Data Structures: Series vs DataFrame

**Series**: One-dimensional labeled array (like a single column).
**DataFrame**: Two-dimensional labeled data structure (like a table with multiple columns).

In [27]:
# Accessing a single column returns a Series
classData['Age']

0    20
1    21
2    19
3    22
4    21
Name: Age, dtype: int64

## Creating Series from NumPy

In [ ]:
import numpy as np
series1 = pd.Series(np.random.rand(30))

In [29]:
series1

0     0.123456
1     0.654321
...
29    0.987654
dtype: float64

In [32]:
# Creating a larger random DataFrame
newDf = pd.DataFrame(np.random.rand(330,5), columns=['A','B','C','D','E'])

In [33]:
type(newDf)

pandas.core.frame.DataFrame

## GroupBy Operations

In [ ]:
# Example dataset for GroupBy
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}
df = pd.DataFrame(data)

In [13]:
by_comp = df.groupby('Company')
by_comp.count()

         Person  Sales
Company
FB            2      2
GOOG          2      2
MSFT          2      2

In [14]:
# Detailed statistical summary by group
by_comp.describe()

        Sales
        count   mean         std    min     25%    50%     75%    max
Company
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0